    [gmleft, gmright, gmbothleft, gmbothright] = ...
       build_test_models(refdata, mdata, 0);

%%statesb = cat(2, zeros(12,1), [1;0;0;0;0;0; 1;0;0;0;0;0], [0;0;0;pi/2;0;0; 0;0;0;pi/2;0;0]);
statesb = cat(2, zeros(12,1), [1;0;0;0;0;0; 1;0;0;0;0;0], ...
	      [0;0;0;pi/2;0;0; 0;0;0;pi/2;0;0], [0;1;0;pi/2;0;0; 0;1;0;pi/2;0;0] );
,
    [Wbothleft, Wepbothleft, Mbothleft, Mepbothleft, Mfbothleft, Jhleft, Jhepleft] = ...
        golfer_mobility(gmbothleft, statesb);
    [Wbothright, Wepbothright, Mbothright, Mepbothright, Mfbothright, Jhright, Jhepright] = ...
        golfer_mobility(gmbothright, statesb);
    [Wright, Wepright, Mright, Mepright, Mfright] = ...
        golfer_mobility(gmright, statesb(1:6, :));
    [Wleft, Wepleft, Mleft, Mepleft, Mfleft] = ...
        golfer_mobility(gmleft, statesb(7:12, :));



