function a=get_alias(isright,mnames,nlist)
  %    a=get_alias(isright,mnames,nlist)
  % Function which finds aliases for the marker names in mnames. If
  % the third argument is given, then the list of markers in nlist
  % defines the entries in the lookup table (hash) returned in a.
  %
  % Input
  %    isright  ->  a boolean. 1 if right leg, 0 if left.
  %    mnames   ->  cell array of marker names.
  %    nlist    ->  (optional) cell array of marker names. Will be
  %                 matched with names in mnames using the known
  %                 aliases.
    
  % Kjartan Halvorsen
  % 2003-01-09
    
path_to_config=config_path_eqdist;

try
  eqconf=load([path_to_config filesep 'eqdist_def']);
  alilist=eqconf.alilist;
  sgmlist=eqconf.sgmlist;
  jcdlist=eqconf.jcdlist;
catch
  % Could not load the definition file. Assume none exists, and
  % make a new one.
  alilist={'mct_med',{};...
	   'mct_lat',{};...
	   'mct_dorsal',{};...
	   'fetlock_med',{};...
	   'fetlock_lat',{};...
	   'pastern_dorsal',{};...
	   'pastern_med',{};...
	   'pastern_lat',{};...
	   'coffin_dorsal',{};...
	   'coffin_med',{};...
	   'coffin_lat',{};...
	   'hoof_lat',{};...
	   'hoof_dorsal',{}};


  sgmlist={'canon',{'mct_lat','mct_dorsal','fetlock_lat'};...
	   'longpastern',{'pastern_lat','pastern_dorsal'};...
	   'shortpastern',{};...	
	   'hoof',{'coffin_lat','coffin_dorsal','hoof_lat'}};
  
  jcdlist={'jc_fetlock',{'fetlock_lat','fetlock_med'};...
	   'jc_pastern',{'pastern_lat','pastern_med'};...
	   'jc_coffin',{'coffin_lat','coffin_med'};...
	   'jc_carpus',{'mct_lat','mct_med'}};
  
  save([path_to_config filesep 'eqdist_def'],'alilist','sgmlist','jcdlist');
end

[mlist,foundalias]=reducealias2(alilist,mnames);

if nargin==3
  % Find matching names
  [matchlist,notok]=matchalias(alilist,nlist,mnames);

  if ~notok % Sucessfully found matches.
    a=fliplr(matchlist);
    return
  end
end

if foundalias
  % all aliases found. Continue
else
  % The user has adopted an unknown naming scheme. Fire up the
  % identify_markers gui to learn the scheme.

  if isright
    imname='eqdist_markers_right.png';
    [im,map]=imread(imname,'png');
    if (size(im,3)==1)
      im=ind2rgb(im,map);
    end
    
    if length(mnames)==13
      markerid={'mct_med',[1 0.98];...
		'mct_lat',[0 0.98];...
		'mct_dorsal',[0 0.71];...
		'fetlock_med',[1 0.45];...
		'fetlock_lat',[0 0.45];...
		'pastern_dorsal',[1 0.335];...
		'pastern_med',[1 0.25];...
		'pastern_lat',[0 0.31];...
		'coffin_dorsal',[1 0.06];...
		'coffin_med',[1 0.16];...
		'coffin_lat',[0 0.22];...
		'hoof_lat',[0 0.13];...
		'hoof_dorsal',[0 0.05]};
    else
      markerid={'mct_lat',[0 0.98];...
		'mct_dorsal',[0 0.71];...
		'fetlock_lat',[0 0.45];...
		'pastern_dorsal',[1 0.335];...
		'pastern_lat',[0 0.31];...
		'coffin_dorsal',[1 0.06];...
		'coffin_lat',[0 0.22];...
		'hoof_lat',[0 0.13]};
    end      
  else
    imname='eqdist_markers_left.png';
    [im,map]=imread(imname,'png');
    if (size(im,3)==1)
      im=ind2rgb(im,map);
    end

    if length(mnames)==13
      markerid={'mct_med',[0 0.98];...
		'mct_lat',[1 0.98];...
		'mct_dorsal',[1 0.71];...
		'fetlock_med',[0 0.45];...
		'fetlock_lat',[1 0.45];...
		'pastern_dorsal',[0 0.335];...
		'pastern_med',[0 0.25];...
		'pastern_lat',[1 0.31];...
		'coffin_dorsal',[0 0.06];...
		'coffin_med',[0 0.16];...
		'coffin_lat',[1 0.22];...
		'hoof_lat',[1 0.13];...
		'hoof_dorsal',[1 0.05]};
    else
      markerid={'mct_lat',[1 0.98];...
		'mct_dorsal',[1 0.71];...
		'fetlock_lat',[1 0.45];...
		'pastern_dorsal',[0 0.335];...
		'pastern_lat',[1 0.31];...
		'coffin_dorsal',[0 0.06];...
		'coffin_lat',[1 0.22];...
		'hoof_lat',[1 0.13]};
    end
    
  end

  if ~foundalias
    % No alias found
    mlist=identify_markers(markerid,im,mnames)
  else
    [sortednames,ind1,ind2]=intersect(markerid(:,1),mlist(:,1));
    [ind1,ind1sort]=sort(ind1);
    ind2=ind2(ind1sort);
    mlist=identify_markers(markerid(ind1,:),im,mnames,mlist(ind2,:))
  end

  if isempty(mlist)
    error('The user cancelled the identify_markers dialog')
    return
  end
  
  % Save the new aliases
  answer=questdlg('Update the list of marker names?','Update aliases',...
		  'Yes','No','Yes');

  if strcmp(answer,'Yes')
    % backup.
    save([path_to_config filesep 'eqdist_def_old'],'alilist', ...
	 'sgmlist','jcdlist'); 

    for i=1:size(mlist,1)
      [slask,ind1]=intersect(alilist(:,1),mlist(i,1));
      if ~isempty(ind1)
	alilist{ind1(1),2}=cat(2,alilist{ind1(1),2},mlist(i,2));
      end
    end
    
    save([path_to_config filesep 'eqdist_def'],'alilist','sgmlist','jcdlist');
  end
end

if nargin==2
  a=mlist;
  return
else % Find matching names
  matchlist=matchalias(alilist,nlist,mnames);
  a=fliplr(matchlist);
end

  